- name: Generate CSS
  run: |
    TODAY="2026-02-03"

    cat > today.css << EOF
    .timetable-day {
        display: none !important;
    }

    .timetable-day[data-date="$TODAY"] {
        display: block !important;
    }
    EOF

